version: '3.8'

services:
  db:
    image: postgres:17
    container_name: inovacion-db
    restart: always
    environment:
      POSTGRES_USER: inovacion
      POSTGRES_PASSWORD: 181919
    
      POSTGRES_DB: inovaciondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
